import Link from "next/link";
import PreviewCard from "@/components/dashboard/PreviewCard";
import type { AccountPreview, BudgetPreview, CurrencyTotal, GoalPreview, InvestmentPreview, SubscriptionPreview, TransactionPreview } from "@/lib/dashboard/dashboard-data";
import type { NewsArticle } from "@/lib/news/types";
import { formatDateOnlyShort, formatMoney, formatTimestampShort } from "@/lib/dashboard/dashboard-format";

const ACCOUNT_EMOJI: Record<string, string> = { banco: "🏦", billetera: "👛", efectivo: "💵", inversion: "📈", cripto: "🪙" };
const ACCOUNT_LABEL: Record<string, string> = { banco: "Banco", billetera: "Billetera", efectivo: "Efectivo", inversion: "Inversión", cripto: "Cripto" };
const ASSET_LABEL: Record<string, string> = { accion: "Acción", etf: "ETF", fondo: "Fondo", cripto: "Cripto", plazo_fijo: "Plazo fijo", inmueble: "Inmueble" };
type Tone = "green" | "amber" | "red" | "blue";
const TONE_CLASS: Record<Tone, string> = { green: "bg-[#4ADE80]", amber: "bg-[#4ADE80]", red: "bg-[#4ADE80]", blue: "bg-[#4ADE80]" };

function ProgressBar({ value, tone }: { value: number; tone: Tone }) {
  return <div className="h-1.5 w-full overflow-hidden rounded-full bg-[#4ADE80]/10"><div className={`h-full rounded-full ${TONE_CLASS[tone]} opacity-75 transition-all duration-700`} style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>;
}
function EmptyState({ text, href, cta }: { text: string; href: string; cta: string }) {
  return <div className="flex h-full min-h-28 flex-col items-center justify-center gap-3 rounded-2xl border border-dashed border-white/10 px-4 py-6 text-center"><p className="text-sm text-white/50">{text}</p><Link href={href} className="rounded-xl bg-[#4ADE80] px-4 py-2 text-sm font-semibold text-[#0B0F14] transition hover:bg-[#4ADE80]/90">{cta}</Link></div>;
}
function TotalsChips({ totals }: { totals: CurrencyTotal[] }) { return totals.length ? <div className="mb-4 flex flex-wrap gap-2">{totals.map((item) => <span key={item.currency} className="rounded-full bg-[#4ADE80]/10 px-2.5 py-0.5 text-xs font-semibold text-[#4ADE80]/80">{formatMoney(item.total, item.currency)}</span>)}</div> : null; }

export function AccountsPreview({ accounts, totals, count }: { accounts: AccountPreview[]; totals: CurrencyTotal[]; count: number }) {
  return <PreviewCard href="/accounts" emoji="🏦" title="Cuentas" subtitle={`${count} ${count === 1 ? "cuenta" : "cuentas"}`} index={0}>{accounts.length === 0 ? <EmptyState text="Aún no registras cuentas." href="/accounts" cta="Agregar cuenta" /> : <><TotalsChips totals={totals} /><ul className="space-y-2">{accounts.map((account) => <li key={account.id} className="flex items-center justify-between gap-3 rounded-2xl bg-black/20 px-3 py-2.5"><div className="flex min-w-0 items-center gap-3"><span className="text-lg">{ACCOUNT_EMOJI[account.type] ?? "💳"}</span><div className="min-w-0"><p className="truncate text-sm font-medium text-white/90">{account.name}</p><p className="text-[11px] text-white/40">{ACCOUNT_LABEL[account.type] ?? account.type}</p></div></div><span className="shrink-0 font-mono text-sm font-semibold text-white/90">{formatMoney(account.balance, account.currency)}</span></li>)}</ul></>}</PreviewCard>;
}

export function TransactionsPreview({ transactions }: { transactions: TransactionPreview[] }) {
  return <PreviewCard href="/transactions" emoji="💸" title="Últimas transacciones" subtitle="Tus movimientos más recientes" index={1} className="lg:col-span-2">{transactions.length === 0 ? <EmptyState text="Todavía no hay movimientos registrados." href="/transactions" cta="Registrar movimiento" /> : <ul className="divide-y divide-white/5">{transactions.map((transaction) => { const isIncome = transaction.type === "ingreso"; const icon = transaction.categoryIcon && !transaction.categoryIcon.includes("arrow-") ? transaction.categoryIcon : (isIncome ? "↓" : "↑"); return <li key={transaction.id} className="flex items-center justify-between gap-3 py-2.5"><div className="flex min-w-0 items-center gap-3"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl text-base ${isIncome ? "bg-[#4ADE80]/10" : "bg-[#F87171]/10"}`}>{icon}</span><div className="min-w-0"><p className="truncate text-sm font-medium text-white/90">{transaction.description}</p><p className="truncate text-[11px] text-white/40">{transaction.categoryName ?? "Sin categoría"} · {transaction.accountName} · {formatTimestampShort(transaction.occurredAt)}</p></div></div><span className={`shrink-0 font-mono text-sm font-semibold ${isIncome ? "text-[#4ADE80]" : "text-[#F87171]"}`}>{isIncome ? "+" : "-"}{formatMoney(transaction.amount, transaction.currency)}</span></li>; })}</ul>}</PreviewCard>;
}

export function BudgetsPreview({ budgets }: { budgets: BudgetPreview[] }) { return <PreviewCard href="/budgets" emoji="📊" title="Presupuestos" subtitle="Consumo del mes" index={2}>{budgets.length === 0 ? <EmptyState text="Define un límite mensual por categoría." href="/budgets" cta="Crear presupuesto" /> : <ul className="space-y-4">{budgets.map((budget) => { const tone: Tone = budget.percentage > 100 ? "red" : budget.percentage >= 80 ? "amber" : "green"; return <li key={budget.id}><div className="mb-1.5 flex items-center justify-between gap-2 text-sm"><span className="truncate text-white/85">{budget.icon ? `${budget.icon} ` : ""}{budget.name}</span><span className="shrink-0 text-xs font-semibold text-[#4ADE80]/75">{budget.percentage}%</span></div><ProgressBar value={budget.percentage} tone={tone} /><p className="mt-1 text-[11px] text-white/40">{formatMoney(budget.spent, budget.currency)} de {formatMoney(budget.limit, budget.currency)}</p></li>; })}</ul>}</PreviewCard>; }
export function GoalsPreview({ goals }: { goals: GoalPreview[] }) { return <PreviewCard href="/goals" emoji="🎯" title="Metas" subtitle="Tu progreso de ahorro" index={3}>{goals.length === 0 ? <EmptyState text="Crea tu primera meta de ahorro." href="/goals" cta="Crear meta" /> : <ul className="space-y-4">{goals.map((goal) => <li key={goal.id}><div className="mb-1.5 flex items-center justify-between gap-2 text-sm"><span className="truncate text-white/85">{goal.name}</span><span className="shrink-0 text-xs font-semibold text-[#4ADE80]/75">{goal.percentage}%</span></div><ProgressBar value={goal.percentage} tone="green" /><p className="mt-1 text-[11px] text-white/40">{formatMoney(goal.current, goal.currency)} de {formatMoney(goal.target, goal.currency)}{goal.targetDate ? ` · hasta ${formatDateOnlyShort(goal.targetDate)}` : ""}</p></li>)}</ul>}</PreviewCard>; }
export function SubscriptionsPreview({ subscriptions, dueSoon }: { subscriptions: SubscriptionPreview[]; dueSoon: number }) { return <PreviewCard href="/subscriptions" emoji="🔁" title="Suscripciones" subtitle={dueSoon > 0 ? `${dueSoon} por cobrar en 7 días` : "Próximos cobros"} index={4}>{subscriptions.length === 0 ? <EmptyState text="Registra tus pagos recurrentes." href="/subscriptions" cta="Agregar suscripción" /> : <ul className="space-y-2">{subscriptions.map((subscription) => { const soon = subscription.daysLeft <= 7; const badge = subscription.daysLeft <= 0 ? "Hoy" : subscription.daysLeft === 1 ? "Mañana" : `En ${subscription.daysLeft} días`; return <li key={subscription.id} className="flex items-center justify-between gap-3 rounded-2xl bg-black/20 px-3 py-2.5"><div className="min-w-0"><p className="truncate text-sm font-medium text-white/90">{subscription.name}</p><p className="text-[11px] text-white/40">{formatDateOnlyShort(subscription.nextChargeDate)} · {formatMoney(subscription.amount, subscription.currency)}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[11px] font-semibold ${soon ? "bg-[#4ADE80]/10 text-[#4ADE80]/80" : "bg-white/10 text-white/60"}`}>{badge}</span></li>; })}</ul>}</PreviewCard>; }
export function InvestmentsPreview({ investments, totals, count }: { investments: InvestmentPreview[]; totals: CurrencyTotal[]; count: number }) { return <PreviewCard href="/investments" emoji="📈" title="Inversiones" subtitle={`${count} ${count === 1 ? "activo" : "activos"}`} index={5}>{investments.length === 0 ? <EmptyState text="Registra tus inversiones para seguirlas." href="/investments" cta="Agregar inversión" /> : <><TotalsChips totals={totals} /><ul className="space-y-2">{investments.map((investment) => { const positive = (investment.returnPct ?? 0) >= 0; return <li key={investment.id} className="flex items-center justify-between gap-3 rounded-2xl bg-black/20 px-3 py-2.5"><div className="min-w-0"><p className="truncate text-sm font-medium text-white/90">{investment.name}</p><p className="text-[11px] text-white/40">{ASSET_LABEL[investment.assetType] ?? investment.assetType} · {formatMoney(investment.value, investment.currency)}</p></div>{investment.returnPct !== null ? <span className="shrink-0 text-xs font-semibold text-[#4ADE80]/75">{positive ? "▲" : "▼"} {Math.abs(investment.returnPct).toFixed(1)}%</span> : null}</li>; })}</ul></>}</PreviewCard>; }
export function NewsPreview({ articles }: { articles: NewsArticle[] }) { return <PreviewCard href="/news" emoji="📰" title="Noticias financieras" subtitle="Se actualizan varias veces al día" index={6} className="md:col-span-2 lg:col-span-2">{articles.length === 0 ? <EmptyState text="Las noticias aparecerán con la próxima actualización." href="/news" cta="Ir a Noticias" /> : <ul className="space-y-3">{articles.map((article) => <li key={article.id} className="rounded-2xl bg-black/20 p-3.5"><div className="flex items-center gap-2 text-[11px] text-white/40"><span>{formatTimestampShort(article.published_at)}</span>{article.relevance_tags?.[0] ? <span className="rounded-full bg-[#4ADE80]/10 px-2 py-0.5 text-[#4ADE80]/70">{article.relevance_tags[0]}</span> : null}</div>{article.url ? <a href={article.url} target="_blank" rel="noreferrer" className="mt-1.5 line-clamp-2 text-sm font-medium leading-snug text-white/90 hover:text-[#4ADE80]">{article.title}</a> : <p className="mt-1.5 line-clamp-2 text-sm font-medium leading-snug text-white/90">{article.title}</p>}</li>)}</ul>}</PreviewCard>; }
export function GuidesPromo() { return <section className="myksh-fade-up relative overflow-hidden rounded-3xl border border-[#4ADE80]/25 bg-gradient-to-br from-[#4ADE80]/15 via-white/[0.04] to-[#4ADE80]/10 p-6 backdrop-blur-md md:col-span-2 lg:col-span-3" style={{ animationDelay: "490ms" }}><div className="flex flex-col items-start gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="text-5xl" role="img" aria-label="Libros">📚</span><div><h2 className="text-lg font-semibold text-white/95">Aprende a invertir con criterio</h2><p className="mt-1 max-w-xl text-sm leading-6 text-white/60">Guías cortas y claras sobre cripto, acciones, fondos y plazos fijos, y cómo registrarlos en MYKSH.</p><div className="mt-3 flex flex-wrap gap-2 text-[11px] text-white/60">{["🪙 Cripto", "📊 Acciones y ETFs", "🏛️ Fondos", "🔒 Plazo fijo"].map((topic) => <span key={topic} className="rounded-full bg-white/10 px-2.5 py-1">{topic}</span>)}</div></div></div><Link href="/guides" className="shrink-0 rounded-xl bg-[#4ADE80] px-5 py-3 text-sm font-semibold text-[#0B0F14] transition hover:bg-[#4ADE80]/90">Explorar guías</Link></div></section>; }
