import { getCachedQuote, setCachedQuote } from "./market-cache";
import type { MarketCurrency, MarketQuote } from "./types";

const FIAT_CODES = new Set(["AED", "ARS", "AUD", "BRL", "CAD", "CHF", "CLP", "CNY", "COP", "CZK", "DKK", "EUR", "GBP", "HKD", "HUF", "IDR", "ILS", "INR", "JPY", "KRW", "MAD", "MXN", "MYR", "NOK", "NZD", "PEN", "PHP", "PLN", "RON", "RUB", "SEK", "SGD", "THB", "TRY", "USD", "ZAR"]);

function quoteFrom(from: string, to: string, rate: number, source: string, updatedAt?: string): MarketQuote { return { from, to, rate, source, updatedAt: updatedAt ?? new Date().toISOString() }; }
async function requestJson(url: string): Promise<unknown> { const response = await fetch(url, { cache: "no-store", next: { revalidate: 21600 }, headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); }
async function getFromFrankfurter(from: string, to: string): Promise<MarketQuote> { const data = (await requestJson(`https://api.frankfurter.dev/v1/latest?base=${encodeURIComponent(from)}&symbols=${encodeURIComponent(to)}`)) as { date?: string; rates?: Record<string, number | undefined> }; const rate = data.rates?.[to]; if (typeof rate !== "number" || !Number.isFinite(rate)) throw new Error("Frankfurter no devolvió la tasa."); return quoteFrom(from, to, rate, "frankfurter_ecb", data.date ? `${data.date}T00:00:00.000Z` : undefined); }
async function getFromExchangeRateHost(from: string, to: string): Promise<MarketQuote> { const data = (await requestJson(`https://api.exchangerate.host/live?source=${encodeURIComponent(from)}&currencies=${encodeURIComponent(to)}`)) as { success?: boolean; quotes?: Record<string, number | undefined>; timestamp?: number }; const rate = data.quotes?.[`${from}${to}`]; if (data.success === false || typeof rate !== "number" || !Number.isFinite(rate)) throw new Error("ExchangeRate.host no devolvió la tasa."); return quoteFrom(from, to, rate, "exchangeratehost", data.timestamp ? new Date(data.timestamp * 1000).toISOString() : undefined); }
const FALLBACK: Record<string, number> = { USDPEN: 3.70, PENUSD: 1 / 3.70, EURPEN: 4.30, PENEUR: 1 / 4.30, CADPEN: 2.70, PENCAD: 1 / 2.70 };
export async function getFiatRate(from: MarketCurrency, to: MarketCurrency): Promise<MarketQuote> { const base = from.toUpperCase(); const target = to.toUpperCase(); if (!FIAT_CODES.has(base) || !FIAT_CODES.has(target)) throw new Error(`Moneda fiat no soportada: ${base}/${target}.`); if (base === target) return quoteFrom(base, target, 1, "identity"); const key = `fiat-${base}-${target}`; const cached = getCachedQuote(key); if (cached) return cached; let quote: MarketQuote; try { quote = await getFromFrankfurter(base, target); } catch { try { quote = await getFromExchangeRateHost(base, target); } catch { const rate = FALLBACK[`${base}${target}`]; if (typeof rate !== "number" || !Number.isFinite(rate)) throw new Error(`No hay una tasa disponible para ${base}/${target}.`); quote = quoteFrom(base, target, rate, "fallback_reference"); } } setCachedQuote(key, quote); return quote; }
