"use client";

import { Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import type { MultiCurrencyAllocationSlice } from "@/app/actions/allocation-multicurrency-actions";

const ASSET_TYPE_LABEL: Record<string, string> = { accion: "Acciones", fondo: "Fondos", cripto: "Cripto", plazo_fijo: "Plazo fijo", inmueble: "Inmuebles" };
const COLORS = ["#4ADE80", "#60A5FA", "#FBBF24", "#F87171", "#A78BFA", "#FB7185"];
function money(value: number, currency: string) { return new Intl.NumberFormat("es-PE", { style: "currency", currency: currency === "USDT" ? "USD" : currency, maximumFractionDigits: 2 }).format(value); }

export default function AllocationPieChartMultiCurrency({ slices, baseCurrency, pendingCount = 0 }: { slices: MultiCurrencyAllocationSlice[]; baseCurrency: string; pendingCount?: number }) {
  const converted = slices.filter((slice) => slice.status === "converted" && slice.convertedAmount !== null);
  const chartData = converted.map((slice) => ({ name: slice.label, assetType: ASSET_TYPE_LABEL[slice.assetType] ?? slice.assetType, value: slice.convertedAmount as number }));
  if (!chartData.length) return <div className="flex min-h-64 items-center justify-center rounded-2xl border border-white/10 bg-white/5 px-5 text-center text-sm text-white/40">No hay inversiones convertibles para mostrar en la distribución.</div>;
  return <div className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="mb-3 flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-white/80">Distribución de la cartera</p><p className="mt-1 text-xs text-white/45">Valores convertidos a {baseCurrency}. Cada segmento representa un activo.</p></div>{pendingCount > 0 && <span className="rounded-full border border-amber-400/30 bg-amber-400/10 px-2 py-1 text-[11px] text-amber-300">{pendingCount} pendiente{pendingCount === 1 ? "" : "s"}</span>}</div><ResponsiveContainer width="100%" height={290}><PieChart><Pie data={chartData} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={58} outerRadius={98} paddingAngle={2}>{chartData.map((slice, index) => <Cell key={`${slice.name}-${index}`} fill={COLORS[index % COLORS.length]} stroke="#0B0F14" />)}</Pie><Tooltip formatter={(value) => [money(Number(value ?? 0), baseCurrency), "Valor"]} labelFormatter={(label, payload) => { const assetType = payload?.[0]?.payload?.assetType; return assetType ? `${label} · ${assetType}` : label; }} contentStyle={{ backgroundColor: "#0B0F14", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8 }} labelStyle={{ color: "#E5E7EB" }} /><Legend wrapperStyle={{ fontSize: 11, color: "#E5E7EB" }} /></PieChart></ResponsiveContainer><div className="mt-3 space-y-2 border-t border-white/10 pt-3">{slices.map((slice) => <div key={slice.key} className="flex items-center justify-between gap-3 text-xs"><div className="min-w-0"><p className="truncate text-white/75">{slice.label}</p><p className="truncate text-[10px] text-white/35">Original: {money(slice.originalAmount, slice.originalCurrency)}{slice.route ? ` · Ruta: ${slice.route.join(" → ")}` : ""}</p></div>{slice.status === "converted" && slice.convertedAmount !== null ? <span className="shrink-0 text-emerald-300">{money(slice.convertedAmount, baseCurrency)}</span> : <span className="shrink-0 text-amber-300">Sin conversión</span>}</div>)}</div></div>;
}
